name: CI/CD Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v2

    - name: Send POST request for static code analysis
      env:
        OWNER: ${{ github.repository_owner }}
        REPO: ${{ github.event.repository.name }}
        TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        response=$(curl -X POST "https://codeanalysis.azurewebsites.net/CodeAnalysis/PerfromStaticCodeAnalysis?owner=${OWNER}&repo=${REPO}&token=${TOKEN}")
        echo "Response: $response"
        result=$(echo $response | jq '.result')
        if [ "$result" != "true" ]; then
          echo "Static code analysis failed."
          exit 1
        fi
        echo "Static code analysis passed."
      shell: bash

    - name: Further build steps
      if: success()
      run: |
        echo "Performing further build steps..."
        # Add your build commands here
