name: Static Code Analysis

on:
  push:
    branches:
      - main
      - master
      - '**/feature/**'

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install curl
      run: sudo apt-get install -y curl

    - name: Perform Static Code Analysis
      run: |
        RESPONSE=$(curl -s -o response.txt -w "%{http_code}" -X POST "https://codeanalysis.azurewebsites.net/CodeAnalysis/PerfromStaticCodeAnalysis?owner=naveenjangala93&repo=StudentManagement&token=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")

        echo "HTTP Response Code: $RESPONSE"
        echo "API Response:"
        cat response.txt
